services:
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony_app
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        networks:
            - symfony_app
    nginx:
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        ports:
            - 80:80
        networks:
            - symfony_app
        depends_on:
            -   php

volumes:
    db_app:

networks:
    symfony_app:
