version: "3.8"

services:
    php:
        image: renantaranto/infnet-tasks-php:latest
        deploy:
            replicas: 4
            restart_policy:
                condition: on-failure
        environment:
            APP_ENV: prod
            APP_DEBUG: 0

    nginx:
        image: renantaranto/infnet-tasks-nginx:latest
        deploy:
            replicas: 4
            restart_policy:
                condition: on-failure
        ports:
            - 80:80

    db:
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
