version: "3.8"

services:
    php:
        image: renantaranto/infnet-tasks-php:latest
        deploy:
            replicas: 4
            restart_policy:
                condition: on-failure
        environment:
            APP_ENV: prod
            APP_DEBUG: 0

    nginx:
        image: renantaranto/infnet-tasks-nginx:latest
        deploy:
            replicas: 4
            restart_policy:
                condition: on-failure
        ports:
            - 80:80
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost/ping" ]
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 5s

    db:
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.47.2
        deploy:
            mode: global
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - target: 8080
              published: 8080
              mode: host
        networks:
            - monitor-net

    prometheus:
        image: prom/prometheus:v2.52.0
        volumes:
            - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - target: 9090
              published: 9090
              mode: host
        networks:
            - monitor-net

    grafana:
        image: grafana/grafana-oss:10.3.1
        ports:
            - target: 3000
              published: 3000
              mode: host
        networks:
            - monitor-net
        volumes:
            - grafana-storage:/var/lib/grafana
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == worker

networks:
    monitor-net:
        driver: overlay

volumes:
    grafana-storage:
