version: "3.8"

services:
    php:
        image: renantaranto/infnet-tasks-php:latest
        deploy:
            replicas: 4
            restart_policy:
                condition: on-failure
        environment:
            APP_ENV: prod
            APP_DEBUG: 0

    nginx:
        image: renantaranto/infnet-tasks-nginx:latest
        deploy:
            replicas: 4
            restart_policy:
                condition: on-failure
        ports:
            - 80:80
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost/ping" ]
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 5s

    db:
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
