name: Build and Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build and Push Docker Images
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and push PHP image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: .docker/php/Dockerfile
                  push: true
                  tags: renantaranto/infnet-tasks-php:latest

            - name: Build and push NGINX image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: .docker/nginx/Dockerfile
                  push: true
                  tags: renantaranto/infnet-tasks-nginx:latest

    deploy:
        name: Deploy to Docker Swarm
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: SSH into EC2 and deploy
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd infnet-tasks
                      git pull origin master
                      docker stack deploy -c docker-compose.yml -c docker-compose.prod.yml infnet-tasks
